# Generated by Django 5.0.6 on 2024-07-08 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, verbose_name='Nombre completo')),
                ('cant_personas', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de personas')),
                ('photo', models.FileField(upload_to='', verbose_name='Foto del DNI')),
                ('email_input', models.EmailField(max_length=254, verbose_name='Email')),
                ('news', models.BooleanField(default=False, verbose_name='Suscripcion')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('plan', models.IntegerField(default=1, verbose_name='Plan')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-created'],
            },
        ),
    ]
