# Generated by Django 5.0.6 on 2024-06-29 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiFormularioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('cant_MiFormularios', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('dni', models.FileField(upload_to='uploads/crud_clientes')),
                ('email_input', models.EmailField(max_length=254, unique=True)),
                ('news', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MiFormulario',
        ),
    ]
