# Generated by Django 5.0.6 on 2024-06-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_clientes', '0002_miformulariomodel_delete_miformulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miformulariomodel',
            name='dni',
        ),
    ]
